### ISSUE TITLE
客户端版本文件丢失

### ISSUE THREAD

**Issue by kongtianxintang** [babykylin/babykylin_scmj#10]
creator 2.0.6
构建项目后,在手机/模拟器上运行,提示旧版本
查看log 说是在res/04/xxx.tet缺少这个文件

**Comment by babykylin** [comment]
可能和你的环境有关，可以加QQ群讨论

**Comment by kongtianxintang** [comment]
😂 cocos版本问题 解决了 多谢




| |
kongtianxintang
邮箱：kongtianxintang@163.com
|

Signature is customized by Netease Mail Master

在2019年05月02日 17:24，幼麟 写道：

可能和你的环境有关，可以加QQ群讨论

**Comment by kongtianxintang** [comment]
cocos版本问题 调用的相应的api已经过时
